import { DataTypes } from 'sequelize';
import initDB from './init';

const models = async () => {
    try {
        const sequelize = await initDB();

        const generatedIDAsPK = {
            type: DataTypes.STRING(20),
            allowNull: false,
            primaryKey: true,
            autoIncrement: false,
            comment: 'generated by discord and assigned. should not be updated',
        };

        const User = sequelize.define(
            'User',
            {
                user_id: {
                    ...generatedIDAsPK,
                    field: 'user_id',
                },
                feedback: {
                    type: DataTypes.INTEGER,
                    default: 0,
                    allowNull: false,
                    comment: 'feedback will be incremented or decremented',
                },
            },
            {
                tableName: 'users',
            }
        );

        const Workshop = sequelize.define(
            'Workshop',
            {
                channel_id: {
                    ...generatedIDAsPK,
                    field: 'channel_id',
                },
                // pilot: {
                //     type: DataTypes.STRING(20),
                //     allowNull: false,
                //     references: {
                //         model: User,
                //         key: 'user_id',
                //     },
                // },
                post_id: {
                    type: DataTypes.STRING(20),
                    allowNull: false,
                    comment:
                        'message id for the post in the #tuning-board channel that corresponds to this workshop. should not be updated',
                },
            },
            {
                tableName: 'workshops',
            }
        );

        // const Tuner = sequelize.define(
        //     'Tuner',
        //     {
        //         workshop: {
        //             type: DataTypes.STRING(20),
        //             allowNull: false,
        //             references: {
        //                 model: Workshop,
        //                 key: 'channel_id',
        //             },
        //         },
        //         user: {
        //             type: DataTypes.STRING(20),
        //             allowNull: false,
        //             references: {
        //                 model: User,
        //                 key: 'user_id',
        //             },
        //         },
        //     },
        //     {
        //         tableName: 'tuners',
        //     }
        // );

        Workshop.belongsTo(User, {
            foreignKey: 'pilot',
            allowNull: false,
        });

        Workshop.belongsToMany(User, {
            through: 'workshop_tuner',
            as: 'tuners',
            foreignKey: 'workshop_id',
        });

        User.belongsToMany(Workshop, {
            through: 'workshop_tuner',
            as: 'workshops',
            foreignKey: 'user_id',
        });

        await sequelize.sync();

        return { Workshop, User };
    } catch (e) {
        console.log(e);
    }
};

export default models;
