import { DataTypes } from 'sequelize';
import db from './init';

const models = async () => {
    try {
        const sequelize = db.use();

        const generatedIDAsPK = {
            type: DataTypes.STRING(20),
            allowNull: false,
            primaryKey: true,
            autoIncrement: false,
            comment: 'generated by discord and assigned. should not be updated',
        };

        const User = sequelize.define(
            'User',
            {
                user_id: {
                    ...generatedIDAsPK,
                    field: 'user_id',
                },
            },
            {
                tableName: 'users',
            }
        );

        const Workshop = sequelize.define(
            'Workshop',
            {
                channel_id: {
                    ...generatedIDAsPK,
                    field: 'channel_id',
                },
                post_id: {
                    type: DataTypes.STRING(20),
                    allowNull: false,
                    comment:
                        'message id for the post in the #tuning-board channel that corresponds to this workshop. should not be updated',
                },
            },
            {
                tableName: 'workshops',
            }
        );

        const Feedback = sequelize.define(
            'Feedback',
            {
                score: {
                    type: DataTypes.INTEGER,
                    allowNull: false,
                },
            },
            {
                tableName: 'feedback',
            }
        );

        const Card = sequelize.define(
            'Card',
            {
                name: {
                    type: DataTypes.STRING,
                    allowNull: false,
                },
                image_normal: {
                    type: DataTypes.STRING,
                    allowNull: false,
                },
                image_art_crop: {
                    type: DataTypes.STRING,
                    allowNull: false,
                },
                color_identity: {
                    type: DataTypes.ARRAY(DataTypes.ENUM('W', 'B', 'R', 'U', 'G')),
                    allowNull: false,
                },
                is_edh_legal: {
                    type: DataTypes.BOOLEAN,
                    allowNull: false,
                },
                is_partner: {
                    type: DataTypes.BOOLEAN,
                    allowNull: false,
                },
                scryfall_id: {
                    type: DataTypes.STRING,
                    allowNull: false,
                    unique: true,
                },
            },
            {
                tableName: 'cards',
            }
        );


        // workshop will have a column called "pilot"
        Workshop.belongsTo(User, {
            foreignKey: 'pilot',
            allowNull: false,
        });

        User.hasMany(Feedback, {
            as: 'feedback',
            foreignKey: 'user_id',
        });
        Feedback.belongsTo(User, {
            foreignKey: 'user_id',
            allowNull: false,
            as: 'user',
        });

        Workshop.belongsToMany(User, {
            through: 'workshop_tuner',
            as: 'tuners',
            foreignKey: 'workshop_id',
        });

        User.belongsToMany(Workshop, {
            through: 'workshop_tuner',
            as: 'workshops',
            foreignKey: 'user_id',
        });

        await sequelize.sync();

        const AllModels = [Workshop, User, Feedback, Card];

        return { Workshop, User, Feedback, Card, AllModels };
    } catch (e) {
        console.log(e);
    }
};

export default models;
