import { DataTypes } from 'sequelize';
import db from './init';

const models = async () => {
    try {
        const sequelize = db.use();

        const generatedIDAsPK = {
            type: DataTypes.STRING(20),
            allowNull: false,
            primaryKey: true,
            autoIncrement: false,
            comment: 'generated by discord and assigned. should not be updated',
        };

        const User = sequelize.define(
            'User',
            {
                user_id: {
                    ...generatedIDAsPK,
                    field: 'user_id',
                },
                // feedback: {
                //     type: DataTypes.INTEGER,
                //     default: 0,
                //     allowNull: false,
                //     comment: 'feedback will be incremented or decremented',
                // },
            },
            {
                tableName: 'users',
            }
        );

        const Workshop = sequelize.define(
            'Workshop',
            {
                channel_id: {
                    ...generatedIDAsPK,
                    field: 'channel_id',
                },
                post_id: {
                    type: DataTypes.STRING(20),
                    allowNull: false,
                    comment:
                        'message id for the post in the #tuning-board channel that corresponds to this workshop. should not be updated',
                },
            },
            {
                tableName: 'workshops',
            }
        );

        const Feedback = sequelize.define(
            'Feedback',
            {
                score: {
                    type: DataTypes.INTEGER,
                    allowNull: false,
                },
            },
            {
                tableName: 'feedback',
            }
        );

        // workshop will have a column called "pilot"
        Workshop.belongsTo(User, {
            foreignKey: 'pilot',
            allowNull: false,
        });

        User.hasMany(Feedback, {
            as: 'feedback',
            foreignKey: 'user_id'
        });
        Feedback.belongsTo(User, {
            foreignKey: 'user_id',
            allowNull: false,
            as: 'user',
        });

        Workshop.belongsToMany(User, {
            through: 'workshop_tuner',
            as: 'tuners',
            foreignKey: 'workshop_id',
        });

        User.belongsToMany(Workshop, {
            through: 'workshop_tuner',
            as: 'workshops',
            foreignKey: 'user_id',
        });

        await sequelize.sync();

        return { Workshop, User, Feedback };
    } catch (e) {
        console.log(e);
    }
};

export default models;
